version: '3'
services:
  coworking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coworking-app
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/Coworking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=iskander12345671
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=iskander12345671
      - FLYWAY_SCHEMAS=public
      - FLYWAY_URL=jdbc:postgresql://db:5432/Coworking
    depends_on:
      - db
  db:
    image: postgres
    container_name: coworking-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iskander12345671
      - POSTGRES_DB=Coworking
    ports:
      - 5433:5432